jasypt:
  encryptor:
    password: arkhyterima

management:
  endpoints:
    web:
      exposure:
        include: logfile, httptrace, auditevents, loggers, env, mappings, threaddump, metrics, info

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    stream:
      bindings:
        BlogCreationOutput:
          destination:  blog-creation
          content-type: application/json
        BlogNotificationInput:
         destination:  blog-notification
         content-type: application/json
        BlogUpdateStatusInput:
          destination:  blog-approval
          content-type: application/json
        BlogKey:
          destination:  blog-key
          content-type: application/json
        BlogNumberPerCategoryInput:
          destination:  blog-number-per-category
          content-type: application/json
        BlogNumberPerCategoryInputV2:
          destination:  blog-number-per-category-v2
          content-type: application/json
        BlogCategoryStatisticOutput:
          destination:  blog-category-statistic
          content-type: application/json
        BlogApprovaltatisticInput:
          destination:  blog-approval-statistic
          content-type: application/json
        BlogApprovalResultStatisticInput:
          destination:  blog-approval-result-statistic
          content-type: application/json
        BlogApprovalStatisticV2Input:
          destination:  blog-approval-statistic-v2
          content-type: application/json
        BlogApprovalResultStatisticV2Input:
          destination:  blog-approval-result-statistic-v2
          content-type: application/json

      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost