jasypt:
  encryptor:
    password: arkhyterima

management:
  endpoints:
    web:
      exposure:
        include: logfile, httptrace, auditevents, loggers, env, mappings, threaddump, metrics, info

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

